import { databases, appwriteConfig, ID } from '../../lib/appwrite';
import { Query } from 'appwrite';

// 1. Folders lana (Sirf current user ke)
const getFolders = async (userId) => {
  // Appwrite mein Query.equal se hum sirf us user ke folders filter karte hain
  const response = await databases.listDocuments(
    appwriteConfig.databaseId,
    appwriteConfig.folderCollectionId,
    [Query.equal('userId', userId)] 
  );
  // Appwrite saara data 'documents' array ke andar bhejta hai
  return response.documents; 
};

// 2. Naya Folder Banana
const createFolder = async (folderData) => {
  // folderData mein hum frontend se { name: "...", userId: "..." } bhejenge
  const response = await databases.createDocument(
    appwriteConfig.databaseId,
    appwriteConfig.folderCollectionId,
    ID.unique(), // Random unique ID generated by Appwrite
    {
      name: folderData.name,
      userId: folderData.userId,
    }
  );
  return response;
};
// 2. Naya Folder Banana
const createFolder = async (folderData) => {
  const response = await databases.createDocument(
    appwriteConfig.databaseId,
    appwriteConfig.folderCollectionId,
    ID.unique(), 
    {
      name: folderData.name,
      userId: folderData.userId,
      section: folderData.section, // Yeh nayi line add karni hai
      parent: folderData.parent    // Yeh nayi line add karni hai
    }
  );
  return response;
};
// 3. Folder Delete Karna
const deleteFolder = async (folderId) => {
  const response = await databases.deleteDocument(
    appwriteConfig.databaseId,
    appwriteConfig.folderCollectionId,
    folderId
  );
  return response;
};


// --- FILES / NOTES FUNCTIONS (Inko hum File upload wale step mein fill karenge) ---
const getFiles = async (folderId) => {
  return []; 
};

const uploadFile = async (formData) => {
  return {};
};

const uploadLink = async (linkData) => {
  return {};
};

const fetchMetadata = async (url) => {
  return {};
};

const deleteFile = async (fileId) => {
  return {};
};

const fileService = {
  getFolders,
  createFolder,
  deleteFolder,
  getFiles,
  uploadFile,
  uploadLink,
  fetchMetadata,
  deleteFile
};

export default fileService;