import { useEffect, useState } from 'react';
import { useSelector } from 'react-redux';
import { Edit3, FilePlus, Loader2, Trash2 } from 'lucide-react';
import toast from 'react-hot-toast';
import premiumService from '../features/premium/premiumService';
import AdminGrantPremium from '../components/AdminGrantPremium';

function AdminPanel() {
  const { user } = useSelector((state) => state.auth);
  const [items, setItems] = useState([]); const [title, setTitle] = useState(''); const [type, setType] = useState('note'); const [file, setFile] = useState(null); const [videoUrl, setVideoUrl] = useState(''); const [loading, setLoading] = useState(false);
  const refresh = () => premiumService.listContent(user.$id).then(setItems).catch((error) => toast.error(error.message));
  useEffect(() => {
    if (!user?.$id) return;
    premiumService.listContent(user.$id).then(setItems).catch((error) => toast.error(error.message));
  }, [user?.$id]);
  const submit = async (event) => { event.preventDefault(); setLoading(true); try { await premiumService.uploadContent({ file, title, type, videoUrl, adminId: user.$id }); setTitle(''); setFile(null); setVideoUrl(''); toast.success('Premium content published.'); refresh(); } catch (error) { toast.error(error.message || 'Upload failed.'); } finally { setLoading(false); } };
  const remove = async (item) => { if (!window.confirm(`Delete ${item.title}?`)) return; try { await premiumService.deleteContent(item); setItems((current) => current.filter((entry) => entry.$id !== item.$id)); toast.success('Content deleted.'); } catch (error) { toast.error(error.message || 'Delete failed.'); } };
  const editTitle = async (item) => { const nextTitle = window.prompt('Update title:', item.title); if (!nextTitle || nextTitle.trim() === item.title) return; try { const updated = await premiumService.updateContent(item.$id, { title: nextTitle.trim() }); setItems((current) => current.map((entry) => entry.$id === item.$id ? updated : entry)); toast.success('Content updated.'); } catch (error) { toast.error(error.message || 'Update failed.'); } };
  return <div className="space-y-8"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-purple-500">Admin workspace</p><h1 className="mt-2 text-3xl font-bold text-gray-900 dark:text-white">Premium content control</h1><p className="mt-2 text-sm text-gray-500">Only admin-owned content appears here. Subscribers can never edit these records.</p></div><form onSubmit={submit} className="rounded-xl border border-gray-200 bg-white p-6 dark:border-gray-700 dark:bg-gray-800"><div className="grid gap-4 sm:grid-cols-2"><input required value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Content title" className="rounded-lg border border-gray-300 bg-transparent px-3 py-2 text-sm dark:border-gray-600 dark:text-white" /><select value={type} onChange={(event) => setType(event.target.value)} className="rounded-lg border border-gray-300 bg-gray-50 px-3 py-2 text-sm dark:border-gray-600 dark:bg-gray-900 dark:text-white"><option value="note">Note</option><option value="video">Video link</option><option value="questionbank">Question bank</option><option value="ppt">PPT</option><option value="report">Report</option></select></div>{type === 'video' ? <input required type="url" value={videoUrl} onChange={(event) => setVideoUrl(event.target.value)} placeholder="Unlisted YouTube/Vimeo URL" className="mt-4 w-full rounded-lg border border-gray-300 bg-transparent px-3 py-2 text-sm dark:border-gray-600 dark:text-white" /> : <input required type="file" onChange={(event) => setFile(event.target.files[0])} className="mt-4 block w-full text-sm text-gray-500" />}<button disabled={loading} className="mt-5 inline-flex items-center gap-2 rounded-lg bg-purple-600 px-4 py-2 text-sm font-semibold text-white hover:bg-purple-500 disabled:opacity-60">{loading ? <Loader2 className="h-4 w-4 animate-spin" /> : <FilePlus className="h-4 w-4" />} Publish content</button></form><div className="rounded-xl border border-gray-200 bg-white p-6 dark:border-gray-700 dark:bg-gray-800"><h2 className="font-semibold text-gray-900 dark:text-white">Published premium content</h2><div className="mt-4 divide-y divide-gray-200 dark:divide-gray-700">{items.map((item) => <div key={item.$id} className="flex items-center justify-between gap-4 py-3"><div><p className="text-sm font-medium text-gray-900 dark:text-white">{item.title}</p><p className="text-xs text-gray-500">{item.type}</p></div><div className="flex gap-3"><button onClick={() => editTitle(item)} aria-label={`Edit ${item.title}`} className="text-indigo-500 hover:text-indigo-400"><Edit3 className="h-4 w-4" /></button><button onClick={() => remove(item)} aria-label={`Delete ${item.title}`} className="text-rose-500 hover:text-rose-400"><Trash2 className="h-4 w-4" /></button></div></div>)}</div></div><AdminGrantPremium /></div>;
}

export default AdminPanel;